// Creates renderer/js/brand-svgs.js with the agents' OFFICIAL logos, taken from Lobe Icons
// (@lobehub/icons-static-svg, MIT license). The marks belong to their respective owners.
// Usage: node tools/gen-marks.mjs
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const dir = path.join(root, 'node_modules', '@lobehub', 'icons-static-svg', 'icons');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'node_modules', '@lobehub', 'icons-static-svg', 'package.json'), 'utf8'));

// Claude's logo for Claude Code, OpenAI's "flower" for Codex, each product's own logo for the rest.
const MAP = {
  claude: 'claude-color',
  codex: 'openai',
  agy: 'antigravity-color',
  gemini: 'gemini-color',
  grok: 'grok',
  glm: 'zai',
  copilot: 'githubcopilot',
  cursor: 'cursor',
};

const out = {};
for (const [key, file] of Object.entries(MAP)) {
  const svg = fs.readFileSync(path.join(dir, file + '.svg'), 'utf8');
  const open = svg.match(/^<svg([^>]*)>/);
  if (!open) throw new Error('invalid SVG: ' + file);
  const attrs = ['fill', 'fill-rule', 'clip-rule']
    .map((a) => { const m = open[1].match(new RegExp(`\\s${a}="([^"]*)"`)); return m ? `${a}="${m[1]}"` : ''; })
    .filter(Boolean).join(' ');
  let body = svg.slice(open[0].length).replace(/<\/svg>\s*$/, '').replace(/<title>[\s\S]*?<\/title>/g, '');
  // Unique ids per logo: the gradients and masks will end up in a single global <defs>.
  const ids = [...body.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
  ids.forEach((id, i) => {
    const nid = `fm-${key}-${i}`;
    body = body.split(`id="${id}"`).join(`id="${nid}"`).split(`url(#${id})`).join(`url(#${nid})`)
      .split(`href="#${id}"`).join(`href="#${nid}"`);
  });
  out[key] = { attrs, body: body.trim() };
}

const header = `// Generated by tools/gen-marks.mjs — logos from Lobe Icons ${pkg.version} (MIT license, github.com/lobehub/lobe-icons).\n`
  + '// The marks (Claude, OpenAI/Codex, Antigravity, Gemini, Grok, Z.ai, GitHub Copilot, Cursor) belong to their respective owners.\n';
fs.writeFileSync(path.join(root, 'renderer', 'js', 'brand-svgs.js'),
  header + 'export const BRAND_SVGS = ' + JSON.stringify(out, null, 1) + ';\n');
console.log('logos:', Object.keys(out).join(', '));
